Added 'lain.ux'-style checks for environment vars to be set (I lost data as well!!!).

diff --git a/tools/bin/build_icarus b/tools/bin/build_icarus
--- a/tools/bin/build_icarus
+++ b/tools/bin/build_icarus
@@ -1,14 +1,11 @@
 #!/bin/bash
 
-# Check that $S1_ROOT is not empty (provided by lain.ux)
-if [ -n "$S1_ROOT" ]; then
-  echo "Building testbench using Icarus simulator..."
-  cd $S1_ROOT/run/sim/icarus
-  rm -rf *
-  iverilog -o testbench -c$FILELIST_ICARUS
-  echo -e "Done!"
-else
-  echo "***ERROR***: S1_ROOT variable is undefined. Please refer to S1 Core" \
-       "installation document (docs/INSTALL.TXT) for more detail."
-fi
+if [ -z "$S1_ROOT" ]; then echo "***ERROR***: S1_ROOT variable is undefined, please set it and run 'source sourceme'."; exit 1; fi
+if ! [ -d "$S1_ROOT" ]; then echo "***ERROR***: directory '$S1_ROOT' does not exist, please check it and run 'source sourceme' again."; exit 1; fi
+
+echo "Building testbench using Icarus simulator..."
+cd $S1_ROOT/run/sim/icarus
+rm -rf *
+iverilog -o testbench -c$FILELIST_ICARUS
+echo -e "Done!"
 
diff --git a/tools/bin/build_xst b/tools/bin/build_xst
--- a/tools/bin/build_xst
+++ b/tools/bin/build_xst
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+if [ -z "$S1_ROOT" ]; then echo "***ERROR***: S1_ROOT variable is undefined, please set it and run 'source sourceme'."; exit 1; fi
+if ! [ -d "$S1_ROOT" ]; then echo "***ERROR***: directory '$S1_ROOT' does not exist, please check it and run 'source sourceme' again."; exit 1; fi
+
 cd $S1_ROOT/run/synth/xst
 rm -rf *  # Make clean
 xst -ifn $S1_ROOT/tools/src/build_xst.cmd -ofn synth.log
diff --git a/tools/bin/update_filelist b/tools/bin/update_filelist
--- a/tools/bin/update_filelist
+++ b/tools/bin/update_filelist
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+if [ -z "$S1_ROOT" ]; then echo "***ERROR***: S1_ROOT variable is undefined, please set it and run 'source sourceme'."; exit 1; fi
+if ! [ -d "$S1_ROOT" ]; then echo "***ERROR***: directory '$S1_ROOT' does not exist, please check it and run 'source sourceme' again."; exit 1; fi
+
 # Create the Icarus filelist (for Icarus simulation)
 rm -f $FILELIST_ICARUS
 touch $FILELIST_ICARUS
diff --git a/tools/bin/update_macrocell b/tools/bin/update_macrocell
--- a/tools/bin/update_macrocell
+++ b/tools/bin/update_macrocell
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+if [ -z "$S1_ROOT" ]; then echo "***ERROR***: S1_ROOT variable is undefined, please set it and run 'source sourceme'."; exit 1; fi
+if ! [ -d "$S1_ROOT" ]; then echo "***ERROR***: directory '$S1_ROOT' does not exist, please check it and run 'source sourceme' again."; exit 1; fi
+
 SRC_LIB=$S1_ROOT/hdl/behav/sparc_libs/u1_lib.v
 DST_LIB=$S1_ROOT/hdl/macrocell/sparc_libs/u1_lib.v
 rm -f $DST_LIB
diff --git a/tools/bin/update_sparccore b/tools/bin/update_sparccore
--- a/tools/bin/update_sparccore
+++ b/tools/bin/update_sparccore
@@ -15,6 +15,12 @@ if ( (test $# != 1) || ((test $1 != "-me") && (test $1 != "-se") && (test $1 != 
   exit 1;
 fi
 
+if [ -z "$S1_ROOT" ]; then echo "***ERROR***: S1_ROOT variable is undefined, please set it and run 'source sourceme'."; exit 1; fi
+if ! [ -d "$S1_ROOT" ]; then echo "***ERROR***: directory '$S1_ROOT' does not exist, please check it and run 'source sourceme' again."; exit 1; fi
+
+if [ -z "$T1_ROOT" ]; then echo "***ERROR***: T1_ROOT variable is undefined, please set it and run 'source sourceme'."; exit 1; fi
+if ! [ -d "$T1_ROOT" ]; then echo "***ERROR***: directory '$T1_ROOT' does not exist, please check it and run 'source sourceme' again."; exit 1; fi
+
 # Set source and destination directories
 SRC_DIR=$T1_ROOT/design/sys/iop
 DST_DIR=$S1_ROOT/hdl/rtl/sparc_core
